# latexpp config for MyDocument.tex
#
# This is YAML syntax -- google "YAML tutorial" to get a quick intro.  Be
# careful with spaces since indentation is important.

# the master LaTeX document -- this file will not be modified, all output will
# be produced in the output_dir
fname: 'resume.tex'

# output file(s) will be created in this directory, originals will not be
# modified
output_dir: 'latexpp_output'

# main document file name in the output directory
output_fname: 'filled-resume.tex'

# specify list of fixes to apply, in the given order
fixes:

  # replace \input{...} directives by the contents of the included file
  - 'latexpp.fixes.input.EvalInput'

  # remove all comments
  - 'latexpp.fixes.comments.RemoveComments'

  # copy any style files (.sty) that are used in the document and that
  # are present in the current directory to the output directory
  - 'latexpp.fixes.usepackage.CopyLocalPkgs'

  # copy figure files to the output directory and rename them fig-1.xxx,
  # fig-2.xxx, etc.
  - 'latexpp.fixes.figures.CopyAndRenameFigs'

  # Replace \bibliography{...} by \input{xxx.bbl} and copy the bbl file to the
  # output directory.  Make sure you run (pdf)latex on the main docuemnt
  # before running latexpp
  - 'latexpp.fixes.bib.CopyAndInputBbl'

  # Expand some macros. Latexpp doesn't parse \newcommand's, so you need to
  # specify here the LaTeX code that the macro should be expanded to. If the
  # macro has arguments, specify the nature of the arguments here in the
  # 'argspec:' key (a '*' is an optional * character, a '[' one optional
  # square-bracket-delimited argument, and a '{' is a mandatory argument). The
  # argument values are available via the placeholders %(1)s, %(2)s, etc. Make
  # sure to use single quotes for strings that contain \ backslashes.
  - name: 'latexpp.fixes.macro_subst.Subst'
    config:
      macros:
        # \tr         -->  \operatorname{tr}
        tr: '\operatorname{tr}'
        # \ket{\psi}  -->  \lvert{\psi}\rangle
        ket:
          argspec: '{'
          repl: '\lvert{%(1)s}\rangle'
        # \braket{\psi}{\phi}  -->  \langle{\psi}\vert{\phi}\rangle
        braket:
          argspec: '{{'
          repl: '\langle{%(1)s}\vert{%(2)s}\rangle'
